#
###################################
# Site wide configuration
####################################
#
title: Complex Network Research Group (Murata Lab)
email: 
description: Common resources for Murata Lab members.
url: https://net-titech.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Tokyo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Murata Laboratory
  avatar: net-logo.png
  job: "Complex Network @ Titech"
  bio: "Our laboratory studies behaviors and structures of complex networks."
  email:
  disqus-shortname:
  twitter: 
  facebook: 
  google:
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: net-titech 
  gitlab: 
  stackoverflow: 
  linkedin: 
  skype: 
  xing:
  instagram: 
  lastfm: 
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  youtube: net-titech 
  soundcloud: 
  weibo: 
  flickr:
  500px: 
  codepen:
